authapp/urls.py
from django.urls import path
from .views import signin, signup, signout

app_name = "authapp"
urlpatterns = [
    path('signin/', signin, name='signin'),
    path('signup/', signup, name='signup'),
    path('logout/', signout, name='signout')
]

encyclopedia/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("all", views.all, name="allpages"),
    path("wiki/<str:title>", views.wiki, name="wiki"),
    path("edit_page/<str:title>", views.edit_page, name="edit_page"),
    path("random_page", views.random_page, name="random_page"),
    path("infosource", views.infosource, name="infosource"),
    path("howto", views.howto, name="howto"),
    path("search", views.search, name="search"),
    path("add_page", views.add_page, name="add_page"),
  



]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path
# from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
    # path('', home, name='home'),
     path('auth/', include('authapp.urls'))
]

authapp/models.py
from django.db import models

# Create your models here.

encyclopedia/models.py
from django.db import models

# Create your models here.

authapp/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input100', 'type': 'text', 'name': 'username', 'placeholder': 'Type your username'}))
    password = forms.CharField(widget=forms.TextInput(attrs={'class': 'input100', 'type': 'password', 'name': 'password', 'placeholder': 'Type your username'}))

class RegistrationForm(forms.Form):
    firstname = forms.CharField(widget=forms.TextInput(attrs={'class': 'input100', 'type': 'text', 'name': 'firstname', 'placeholder': 'Type your firstname'}))
    lastname = forms.CharField(widget=forms.TextInput(attrs={'class': 'input100', 'type': 'text', 'name': 'lastname', 'placeholder': 'Type your lastname'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'input100', 'type': 'email', 'name': 'email', 'placeholder': 'Type your email'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input100', 'type': 'text', 'name': 'username', 'placeholder': 'Type your username'}))
    password = forms.CharField(widget=forms.TextInput(attrs={'class': 'input100', 'type': 'password', 'name': 'password', 'placeholder': 'Type your password'}))
    confirm_password = forms.CharField(widget=forms.TextInput(attrs={'class': 'input100', 'type': 'password', 'name': 'confirm-password', 'placeholder': 'Type your password again'}))

authapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse







from django.urls import reverse
from django.contrib import auth

from .forms import LoginForm, RegistrationForm      

def signin(request):
    forms = LoginForm()
    if request.method == 'POST':
        forms = LoginForm(request.POST)
        if forms.is_valid():
            username = forms.cleaned_data['username']
            password = forms.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('home')
    context = {
        'form': forms
    }
    return render(request, 'authapp/signin.html', context)


def signup(request):
    forms = RegistrationForm()
    if request.method == 'POST':
        forms = RegistrationForm(request.POST)
        if forms.is_valid():
            firstname = forms.cleaned_data['firstname']
            lastname = forms.cleaned_data['lastname']
            email = forms.cleaned_data['email']
            username = forms.cleaned_data['username']
            password = forms.cleaned_data['password']
            confirm_password = forms.cleaned_data['confirm_password']
            if password == confirm_password:
                try:
                    User.objects.create_user(username=username, password=password, email=email, first_name=firstname, last_name=lastname)
                    return redirect('authapp:signin')
                except:
                    context = {
                        'form': forms,
                        'error': 'This Username Already exists!'
                    }
                    return render(request, 'authapp/signup.html', context)
    context = {
        'form': forms
    }
    return render(request, 'authapp/signup.html', context)

def signout(request):
    logout(request)
    return redirect('authapp:signin')

encyclopedia/views.py
import markdown2
import random
import re
from django.shortcuts import render, redirect, HttpResponse
from . import util
pagelist = util.list_entries()
from markdown2 import Markdown
from django.contrib.auth import authenticate, login, logout

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def infosource(request):
    return render(request, "encyclopedia/infosource.html", {
        "entries": util.list_entries()
    })


def howto(request):
    return render(request, "encyclopedia/howto.html", {
        "entries": util.list_entries()
    })


def all(request):
    return render(request, "encyclopedia/all.html", {
        "entries": util.list_entries()
    })


def wiki(request, title):
    pagelist = util.list_entries()

    if title in pagelist:
        content = util.get_entry(title)

        return render(request, "encyclopedia/page.html", {
            "title": title,
            "content": markdown2.markdown(content)
            # send title and content to HTML
        })
    else:
        return render(request, "encyclopedia/error.html", {
            'error_message': 'that page does not exist'
        })

# random page


def random_page(request):

    # random no. in [0-len[pagelist]-1]]
    r = random.randint(0, len(pagelist)-1)
    title = pagelist[r]

    return redirect(wiki, title=title)  # redirect to this page

# search


def search(request):
    if request.method == 'POST':
        term = request.POST
        term = term['text']
        searchlist = []

        for page in pagelist:

            if re.search(term.lower(), page.lower()):  # case in sensitive
                searchlist.append(page)
        if len(searchlist) == 0:  # searchlist is empty
            return render(request, "encyclopedia/error.html", {
                'error_message': f' Oops! looks like no results for \'{term}\' '
            })

    return render(request, "encyclopedia/search.html", {
        'entries': searchlist
    })

# new page


def add_page(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        print(f'title:{title}')
        print(f'content:{content}')
        if title in pagelist:
            return render(request, "encyclopedia/add.html", {
                'available': True
                # page already exists
            })
        else:
            util.save_entry(title, content)
            return redirect(wiki, title=title)
    return render(request, "encyclopedia/add.html", {
        'available': False

    })

# edit markdown


def edit_page(request, title):
    pagecontent = util.get_entry(title)
    if request.method == 'GET':
        return render(request, "encyclopedia/edit.html", {
            'title': title,
            'content': pagecontent
        })
    if request.method == 'POST':
        pagecontent = request.POST.get('newcontent')
        util.save_entry(title, pagecontent)
        return redirect(wiki, title=title)

wiki/views.py
# from django.shortcuts import render
# from django.contrib.auth.decorators import login_required
# from django.contrib.auth.models import User

# @login_required(login_url='authapp:signin')
# def home(request):
#     return render(request, 'encyclopedia/index.html')

authapp/templates/authapp/base.html
<!DOCTYPE html>
<html lang="en">
	{% load static %}
<head>
	
		<style>
	@media (min-width: 600px) {
		h1 {
			font-size:5vw;
		}
	}

	@media (max-width: 599px) {
		h1 {
			font-size:4vw;
		}
	}
	@media (min-width: 359px) {
	h1 {
		font-size:9vw;
		}
		
	}
	@media only screen and (max-width: 600px) {
  body {
    color: rgb(230, 173, 173);
  }
}





/*//////////////////////////////////////////////////////////////////
[ FONT ]*/

@font-face {
  font-family: Poppins-Regular;
  src: url('../fonts/poppins/Poppins-Regular.ttf'); 
}

@font-face {
  font-family: Poppins-Medium;
  src: url('../fonts/poppins/Poppins-Medium.ttf'); 
}

@font-face {
  font-family: Poppins-Bold;
  src: url('../fonts/poppins/Poppins-Bold.ttf'); 
}

@font-face {
  font-family: Poppins-SemiBold;
  src: url('../fonts/poppins/Poppins-SemiBold.ttf'); 
}




/*//////////////////////////////////////////////////////////////////
[ RESTYLE TAG ]*/

* {
	margin: 0px; 
	padding: 0px; 
	box-sizing: border-box;
}

body, html {
	height: 100%;
	font-family: Poppins-Regular, sans-serif;
}

/*---------------------------------------------*/
a {
	font-family: Poppins-Regular;
	font-size: 14px;
	line-height: 1.7;
	color: #666666;
	margin: 0px;
	transition: all 0.4s;
	-webkit-transition: all 0.4s;
  -o-transition: all 0.4s;
  -moz-transition: all 0.4s;
}

a:focus {
	outline: none !important;
}

a:hover {
	text-decoration: none;
  color: #a64bf4;
}

/*---------------------------------------------*/
h1,h2,h3,h4,h5,h6 {
	margin: 0px;
}

p {
	font-family: Poppins-Regular;
	font-size: 14px;
	line-height: 1.7;
	color: #666666;
	margin: 0px;
}

ul, li {
	margin: 0px;
	list-style-type: none;
}


/*---------------------------------------------*/
input {
	outline: none;
	border: none;
}

textarea {
  outline: none;
  border: none;
}

textarea:focus, input:focus {
  border-color: transparent !important;
}

input:focus::-webkit-input-placeholder { color:transparent; }
input:focus:-moz-placeholder { color:transparent; }
input:focus::-moz-placeholder { color:transparent; }
input:focus:-ms-input-placeholder { color:transparent; }

textarea:focus::-webkit-input-placeholder { color:transparent; }
textarea:focus:-moz-placeholder { color:transparent; }
textarea:focus::-moz-placeholder { color:transparent; }
textarea:focus:-ms-input-placeholder { color:transparent; }

input::-webkit-input-placeholder { color: #adadad;}
input:-moz-placeholder { color: #adadad;}
input::-moz-placeholder { color: #adadad;}
input:-ms-input-placeholder { color: #adadad;}

textarea::-webkit-input-placeholder { color: #adadad;}
textarea:-moz-placeholder { color: #adadad;}
textarea::-moz-placeholder { color: #adadad;}
textarea:-ms-input-placeholder { color: #adadad;}

/*---------------------------------------------*/
button {
	outline: none !important;
	border: none;
	background: transparent;
}

button:hover {
	cursor: pointer;
}

iframe {
	border: none !important;
}

/*//////////////////////////////////////////////////////////////////
[ Utility ]*/
.txt1 {
  font-family: Poppins-Regular;
  font-size: 14px;
  line-height: 1.5;
  color: #666666;
}

.txt2 {
  font-family: Poppins-Regular;
  font-size: 14px;
  line-height: 1.5;
  color: #333333;
  text-transform: uppercase;
}

.bg1 {background-color: #3b5998}
.bg2 {background-color: #1da1f2}
.bg3 {background-color: #ea4335}



/*//////////////////////////////////////////////////////////////////
[ login ]*/
.limiter {
  width: 100%;
  margin: 0 auto;
}

.container-login100 {
  width: 100%;  
  min-height: 100vh;
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-items: center;
  padding: 15px;
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
}

.wrap-login100 {
  width: 500px;
  background: #fff;
  border-radius: 10px;
  overflow: hidden;
}


/*------------------------------------------------------------------
[ Form ]*/

.login100-form {
  width: 100%;
}

.login100-form-title {
  display: block;
  font-family: Poppins-Bold;
  font-size: 39px;
  color: #333333;
  line-height: 1.2;
  text-align: center;
}



/*------------------------------------------------------------------
[ Input ]*/

.wrap-input100 {
  width: 100%;
  position: relative;
  border-bottom: 2px solid #d9d9d9;
}

.label-input100 {
  font-family: Poppins-Regular;
  font-size: 14px;
  color: #333333;
  line-height: 1.5;
  padding-left: 7px;
}

.input100 {
  font-family: Poppins-Medium;
  font-size: 16px;
  color: #333333;
  line-height: 1.2;

  display: block;
  width: 100%;
  height: 55px;
  background: transparent;
  padding: 0 7px 0 43px;
}


/*---------------------------------------------*/
.focus-input100 {
  position: absolute;
  display: block;
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
  pointer-events: none;
}

.focus-input100::after {
  content: attr(data-symbol);
  font-family: Material-Design-Iconic-Font;
  color: #adadad;
  font-size: 22px;

  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  align-items: center;
  justify-content: center;
  position: absolute;
  height: calc(100% - 20px);
  bottom: 0;
  left: 0;
  padding-left: 13px;
  padding-top: 3px;
}

.focus-input100::before {
  content: "";
  display: block;
  position: absolute;
  bottom: -2px;
  left: 0;
  width: 0;
  height: 2px;
  background: #7f7f7f;
  -webkit-transition: all 0.4s;
  -o-transition: all 0.4s;
  -moz-transition: all 0.4s;
  transition: all 0.4s;
}


.input100:focus + .focus-input100::before {
  width: 100%;
}

.has-val.input100 + .focus-input100::before {
  width: 100%;
}

.input100:focus + .focus-input100::after {
  color: #a64bf4;
}

.has-val.input100 + .focus-input100::after {
  color: #a64bf4;
}


/*------------------------------------------------------------------
[ Button ]*/
.container-login100-form-btn {
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
}

.wrap-login100-form-btn {
  width: 100%;
  display: block;
  position: relative;
  z-index: 1;
  border-radius: 25px;
  overflow: hidden;
  margin: 0 auto;

  box-shadow: 0 5px 30px 0px rgba(3, 216, 222, 0.2);
  -moz-box-shadow: 0 5px 30px 0px rgba(3, 216, 222, 0.2);
  -webkit-box-shadow: 0 5px 30px 0px rgba(3, 216, 222, 0.2);
  -o-box-shadow: 0 5px 30px 0px rgba(3, 216, 222, 0.2);
  -ms-box-shadow: 0 5px 30px 0px rgba(3, 216, 222, 0.2);
}

.login100-form-bgbtn {
  position: absolute;
  z-index: -1;
  width: 300%;
  height: 100%;
  background: #a64bf4;
  background: -webkit-linear-gradient(right, #00dbde, #fc00ff, #00dbde, #fc00ff);
  background: -o-linear-gradient(right, #00dbde, #fc00ff, #00dbde, #fc00ff);
  background: -moz-linear-gradient(right, #00dbde, #fc00ff, #00dbde, #fc00ff);
  background: linear-gradient(right, #00dbde, #fc00ff, #00dbde, #fc00ff);
  top: 0;
  left: -100%;

  -webkit-transition: all 0.4s;
  -o-transition: all 0.4s;
  -moz-transition: all 0.4s;
  transition: all 0.4s;
}

.login100-form-btn {
  font-family: Poppins-Medium;
  font-size: 16px;
  color: #fff;
  line-height: 1.2;
  text-transform: uppercase;

  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 0 20px;
  width: 100%;
  height: 50px;
}

.wrap-login100-form-btn:hover .login100-form-bgbtn {
  left: 0;
}


/*------------------------------------------------------------------
[ Alert validate ]*/

.validate-input {
  position: relative;
}

.alert-validate::before {
  content: attr(data-validate);
  position: absolute;
  max-width: 70%;
  background-color: #fff;
  border: 1px solid #c80000;
  border-radius: 2px;
  padding: 4px 25px 4px 10px;
  bottom: calc((100% - 20px) / 2);
  -webkit-transform: translateY(50%);
  -moz-transform: translateY(50%);
  -ms-transform: translateY(50%);
  -o-transform: translateY(50%);
  transform: translateY(50%);
  right: 2px;
  pointer-events: none;

  font-family: Poppins-Regular;
  color: #c80000;
  font-size: 13px;
  line-height: 1.4;
  text-align: left;

  visibility: hidden;
  opacity: 0;

  -webkit-transition: opacity 0.4s;
  -o-transition: opacity 0.4s;
  -moz-transition: opacity 0.4s;
  transition: opacity 0.4s;
}

.alert-validate::after {
  content: "\f06a";
  font-family: FontAwesome;
  display: block;
  position: absolute;
  color: #c80000;
  font-size: 16px;
  bottom: calc((100% - 20px) / 2);
  -webkit-transform: translateY(50%);
  -moz-transform: translateY(50%);
  -ms-transform: translateY(50%);
  -o-transform: translateY(50%);
  transform: translateY(50%);
  right: 8px;
}

.alert-validate:hover:before {
  visibility: visible;
  opacity: 1;
}

@media (max-width: 992px) {
  .alert-validate::before {
    visibility: visible;
    opacity: 1;
  }
}


/*//////////////////////////////////////////////////////////////////
[ Social item ]*/
.login100-social-item {
  font-size: 25px;
  color: #fff;

  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 50px;
  height: 50px;
  border-radius: 50%;
  margin: 5px;
}

.login100-social-item:hover {
  color: #fff;
  background-color: #333333;
}

/*//////////////////////////////////////////////////////////////////
[ Responsive ]*/

@media (max-width: 576px) {
  .wrap-login100 {
    padding-left: 15px;
    padding-right: 15px;
  }
} 
</style>
		
	
	<title>SterlingWiki Signin</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
			
	<link href="https://azermstorage.blob.core.windows.net/appimages/favicon.png" rel="icon">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
    {% block content %}
    {% endblock %}
	
<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

authapp/templates/authapp/home.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
<div class="container-login100" style="background-image: url({% static 'images/bg-01.jpg' %})">
    <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
        <div class="m-b-23">
            <h2>Welcome {{ request.user }}!</h2>
            <span class="focus-input100" data-symbol="&#xf206;"></span>
        </div>
        <div class="m-b-23">
            <h5>Name: {{ request.user.first_name }} {{ request.user.last_name }}</h5>
            <span class="focus-input100" data-symbol="&#xf206;"></span>
        </div>
        <div class="m-b-23">
            <h5>Email: {{ request.user.email }}</h5>
            <span class="focus-input100" data-symbol="&#xf206;"></span>
        </div>
        <div class="m-b-23">
            <a href="{% url 'signout' %}" class="btn btn-primary">Logout</a>
            <span class="focus-input100" data-symbol="&#xf206;"></span>
        </div>
    </div>
</div>
{% endblock %}

authapp/templates/authapp/signin.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}




<div class="limiter">
	<div class="container-login100" style="background-image: linear-gradient(rgba(10, 0, 39, 0.966), rgba(253, 215, 215, 0.877)), url(https://azermstorage.blob.core.windows.net/appimages/bdp.png); background-repeat: repeat-y; background-size: 100%;">
		<div class="wrap-login100 p-l-55 p-r-55 p-t-55 p-b-24" style=" background-image: linear-gradient(rgba(255, 255, 255, 0.911), rgba(252, 252, 252, 0.938)), url(https://azermstorage.blob.core.windows.net/appimages/bdp.png); background-repeat: repeat-y; background-size: 100%; border-radius: 60px;">
			<form class="login100-form validate-form" method="POST">
				{% csrf_token %}
				<div style="text-align: center; justify-content: center;">
					
				<img style=" align-self: center; height: 79px; width: 73px;" src="https://azermstorage.blob.core.windows.net/appimages/sterlingbig.png" alt="logo" class="logo">
				<h1 style="font-family: 'Playfair Display', sans-serif; text-align: center; color: rgb(0, 0, 0); text-shadow: 1px 2px 3px #ffffff; font-size:5vw; font-weight: normal;">     Sterling Wiki</h1> 
			<b style="font-family: 'Playfair Display', sans-serif; text-align: center; color: rgb(0, 0, 0); text-shadow: 1px 2px 3px #ffffff;"> (A Project Prototype)</b>
			</div>
			<br>
			<b style="font-family: 'Playfair Display', sans-serif; text-align: center; color: rgb(0, 0, 0); text-shadow: 1px 2px 3px #ffffff;"> Sign-in with: Username: testuser |  Password: abc123</b>
		
				
			<br> <br> 
				

				<div class="wrap-input100 validate-input m-b-23" data-validate = "Username is reauired">
					<span class="label-input100"> <b> Username </b></span>
					<!-- <input class="input100" type="text" name="username" placeholder="Type your username"> -->
					{{ form.username }}
					<span class="focus-input100" data-symbol="&#xf206;"></span>
				</div>

				<div class="wrap-input100 validate-input" data-validate="Password is required">
					<span class="label-input100"><b> Password </b></span>
					<!-- <input class="input100" type="password" name="pass" placeholder="Type your password"> -->
					{{ form.password }}
					<span class="focus-input100" data-symbol="&#xf190;"></span>
				</div>
				
				<div class="text-right p-t-8 p-b-31">
					
				</div>
				
				<div class="container-login100-form-btn">
					<div class="wrap-login100-form-btn">
						<div class="login100-form-bgbtn"></div>
						<button class="login100-form-btn">
							Login
						</button>
					
					</div> 
					
				</div>
				<div style="text-align: center;">
				<br>
					or sign up now <a href="{% url 'authapp:signup' %} " style="color: rgb(253, 0, 0);
					text-shadow: 0.8px 0.8px 0.8px  #000000; padding-left: 0.5em;">  Sign Up</a> </div>
				
				<div class="flex-col-c p-t-20">
				
					<!-- <p> <b> Or Sign Up Now  </b><a href="{% url 'authapp:signup' %}" style="color: red; padding: 4px;"  class="txt2">
					<b style="color: rgb(253, 0, 0);
					text-shadow: 0.8px 0.8px 0.8px  #000000;""> Sign Up </b> <br>   -->
					
					<br>
					<br><b style="font-family: 'Poppins', sans-serif; font-size: x-small;">  Powered by</b>  <img  style="   height: 40px; width: 90px;" src="https://azermstorage.blob.core.windows.net/appimages/dataoffice2.png" alt="logo">
		
				</a> </p>	
					
				</div>
			</form>
		</div>
	</div>
</div>


{% endblock %}

encyclopedia/templates/encyclopedia/all.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
SterlingWiki
{% endblock %}

{% block body %}
{% load static %}

<style>
    #container {
        display: flex;
        flex-wrap: wrap;
    }

    #container > div {
        background-color: rgb(255, 255, 255);
        font-size: 17px;
        margin: 20px;
        padding: 10px;
        width: 250px;
       max-height: 70px;
       overflow: auto;
       overflow: hidden;
    }
</style> <br> 

<h1 style="font-family: 'Playfair Display', sans-serif; text-align: center; font-size: 3.5vw; text-shadow: 0.9px 1px 1px #000000;">  Sterling Wiki Pages </b> <img src="{% static 'encyclopedia/robo4.png' %}" alt="" style="height: 10vw; width: 8vw;"> </h1> 

<div id="container">
    {% for entry in entries %}
    <div style=" background-image: linear-gradient(rgba(10, 0, 39, 0.548), rgba(252, 135, 135, 0.301)); border-radius: 8px; text-align: center; box-shadow: 5px 5px 5px rgb(0, 0, 0);"><b style=" font-family: 'Poppins';text-shadow: 0.5px 0.5px 0.5px #000000;"> <a href="{% url 'wiki' entry %}" style="text-decoration: none; text-shadow: 0.8px 1px 0px  #ffffff; "> {{ entry }} </a> </b></div>
    {% endfor %}
    
</div>



{% endblock %}

encyclopedia/templates/encyclopedia/howto.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
SterlingWiki
{% endblock %}

{% block body %}
{% load static %}
 <br>
 <style>
     .center {
  display: block;
  margin-left: auto;
  margin-right: auto;

}


 </style>
<div class="container">

  <h1 style="font-family: 'Playfair Display', sans-serif; text-align: center;text-shadow: 0.9px 1px 1px #000000; font-size:calc(1em + 2.3vw);"> How To Add and Edit Pages </b></h1> <br> 



{% endblock %}